version: '3.8'

services:
  postgres:
    image: ankane/pgvector
    container_name: rag_pgvector
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: VAIRAVESH123####
      POSTGRES_DB: rag_chat
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
